server:
  port: 443
  ssl:
    key-store: classpath:www.instudyhouse.ltd.jks
    key-store-password: qj7ul52446xb6z9
    key-store-type: JKS
    key-alias: www.instudyhouse.ltd

spring:
  datasource:
    url: jdbc:mysql://localhost/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lsq2000..


debug:
  false

swagger:
  enabled: true
  title: Self-Study-Api
  exclude-path:
    - /error
    - /ops/**

mybatis:
  mapper-locations:
    classpath:com.example.study.mapper/*.xml

#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 设置打印sql语句

