server:
  port: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lsq2000..

debug:
  false

swagger:
  enabled: true
  title: Self-Study-Api
  exclude-path:
    - /error
    - /ops/**

mybatis:
  mapper-locations:
    classpath:com.example.study.mapper/*.xml

#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 设置打印sql语句

